### ISSUE TITLE
Fauk to build with boost 1.90

### ISSUE THREAD

**Issue by marillat** [HomeOfVapourSynthEvolution/VapourSynth-NNEDI3CL#3]
I don't know if this filter is still maintained.
GCC 15 amd64
```
In file included from /usr/include/CL/cl.h:20,
                 from /usr/include/boost/compute/cl.hpp:19,
                 from /usr/include/boost/compute/config.hpp:16,
                 from /usr/include/boost/compute/buffer.hpp:14,
                 from /usr/include/boost/compute/core.hpp:18,
                 from ../NNEDI3CL/NNEDI3CL.cpp:48:
/usr/include/CL/cl_version.h:22:104: note: ‘#pragma message: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0)’
   22 | #pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0)")
      |                                                                                                        ^
In file included from /usr/include/boost/compute/command_queue.hpp:26,
                 from /usr/include/boost/compute/core.hpp:19:
/usr/include/boost/compute/image/image1d.hpp: In constructor ‘boost::compute::image1d::image1d(const boost::compute::context&, size_t, const boost::compute::image_format&, cl_mem_flags, void*)’:
/usr/include/boost/compute/image/image1d.hpp:65:14: error: ‘cl_image_desc’ {aka ‘struct _cl_image_desc’} has no member named ‘mem_object’
   65 |         desc.mem_object = 0;
      |              ^~~~~~~~~~
In file included from /usr/include/boost/compute/command_queue.hpp:27:
/usr/include/boost/compute/image/image2d.hpp: In constructor ‘boost::compute::image2d::image2d(const boost::compute::context&, size_t, size_t, const boost::compute::image_format&, cl_mem_flags, void*, size_t)’:
/usr/include/boost/compute/image/image2d.hpp:73:14: error: ‘cl_image_desc’ {aka ‘struct _cl_image_desc’} has no member named ‘mem_object’
   73 |         desc.mem_object = 0;
      |              ^~~~~~~~~~
/usr/include/boost/compute/image/image2d.hpp: In constructor ‘boost::compute::image2d::image2d(const boost::compute::context&, cl_mem_flags, const boost::compute::image_format&, size_t, size_t, size_t, void*)’:
/usr/include/boost/compute/image/image2d.hpp:123:14: error: ‘cl_image_desc’ {aka ‘struct _cl_image_desc’} has no member named ‘mem_object’
  123 |         desc.mem_object = 0;
      |              ^~~~~~~~~~
In file included from /usr/include/boost/compute/command_queue.hpp:28:
/usr/include/boost/compute/image/image3d.hpp: In constructor ‘boost::compute::image3d::image3d(const boost::compute::context&, size_t, size_t, size_t, const boost::compute::image_format&, cl_mem_flags, void*, size_t, size_t)’:
/usr/include/boost/compute/image/image3d.hpp:69:14: error: ‘cl_image_desc’ {aka ‘struct _cl_image_desc’} has no member named ‘mem_object’
   69 |         desc.mem_object = 0;
      |              ^~~~~~~~~~
/usr/include/boost/compute/image/image3d.hpp: In constructor ‘boost::compute::image3d::image3d(const boost::compute::context&, cl_mem_flags, const boost::compute::image_format&, size_t, size_t, size_t, size_t, size_t, void*)’:
/usr/include/boost/compute/image/image3d.hpp:123:14: error: ‘cl_image_desc’ {aka ‘struct _cl_image_desc’} has no member named ‘mem_object’
  123 |         desc.mem_object = 0;
      |              ^~~~~~~~~~
../NNEDI3CL/NNEDI3CL.cpp: In function ‘void nnedi3clCreate(const VSMap*, VSMap*, void*, VSCore*, const VSAPI*)’:
../NNEDI3CL/NNEDI3CL.cpp:687:18: error: ‘cl_image_desc’ {aka ‘struct _cl_image_desc’} has no member named ‘mem_object’
  687 |             desc.mem_object = d->weights1Buffer.get();
      |                  ^~~~~~~~~~
ninja: build stopped: subcommand failed.
```

**Comment by HolyWu** [comment]
Probably not maintained any more. Maybe try https://github.com/Jaded-Encoding-Thaumaturgy/vapoursynth-SNEEDIF.

**Comment by HolyWu** [comment]
Or maybe https://github.com/HolyWu/VapourSynth-nnedi3vk.
